/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 mars.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-0bbd08db494b4e2a873c624021248d12
Title: Mars
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Mars/mars.gltf')
  const meshRef = useRef()

  useFrame((state, delta) => {
    if (meshRef.current) {
      meshRef.current.rotation.y += 0.0008 // Adjust the speed as needed
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef} geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={1.979} />
    </group>
  )
}

useGLTF.preload('/Mars/mars.gltf')
